function modal(x) { // pour x...
    var visible = $(".cv-visible")[x]; // cv-visible d'indice x
    var modal = $(".cv-modal")[x]; // cv-modal d'indice x
    var btn = $(".cta-cv")[x]; // cta-cv d'indice x
    var btnText = $(".cta-cv-text")[x]; // cta-cv-text d'indice x
    $(btn).on("click tap", function() { // quand on clique sur cta-cv d'indice x...
        $(visible).toggle(); // cv-visible d'indice x disparait / apparait...
        $(modal).toggle(); // et cv-modal d'indice x apparait / disparait...
        if ($(modal).is(":visible")) { // et si cv-modal d'indice x est visible...
            $(btnText).html("Back"); // cta-cv-text d'indice x affiche "Retour"...
            $(modal).css("display", "flex"); // et cv-modal est en mode flex...
        } else { // sinon...
            $(btnText).html("Read more"); // cta-cv-text d'indice x affiche "En savoir +"...
        }
    });
}
for (var z = 0; z < $(".cv-visible").length; z++) { // pour chaque occurence de cv-visible...
    modal(z); // exécuter la fonction
}